[package]
name = "walleth"
version = "0.1.0"
authors = ["mikesposito"]
license-file = "LICENSE"
readme="README.md"
description = "A (WIP) Rust library for easily create, manage, use and protect Ethereum accounts."
edition = "2021"
repository = "https://github.com/mikesposito/walleth/"
keywords = [
	"language",
	"cli",
	"http-client",
	"api-client",
	"json-selector",
]

[dependencies]
hex = "0.4.3"
bitcoin_hashes = { version = ">= 0.12, <= 0.13" }
sha3 = "0.10.8"
bip32 = { version = "0.5.1" }
secp256k1 = "0.27.0"
rand_core = { version = "0.6", features = ["std"] }
chacha20poly1305 = { version = "0.9.0", features = ["stream"] }
pbkdf2 = { version = "0.12.2" }
sha2 = { version = "0.10.7" }
hmac = { version = "0.12.1" }
